/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ErrorResponse;
import io.swagger.model.NewStep;
import io.swagger.model.Step;
import io.swagger.model.Task;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-14T13:49:00.734Z")

@Api(value = "steps", description = "the steps API")
public interface StepsApi {

    @ApiOperation(value = "Get an execution", notes = "Get the execution with the corresponding id", response = Task.class, tags={ "step", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Information returned correctly", response = Task.class) })
    
    @RequestMapping(value = "/steps/{step_id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Task> getStepById(@ApiParam(value = "Task ID",required=true ) @PathVariable("step_id") Long stepId);


    @ApiOperation(value = "Creation of a new step", notes = "Creation of a new step", response = Step.class, tags={ "step", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Information returned correctly", response = Step.class),
        @ApiResponse(code = 403, message = "Error on creation of Step", response = ErrorResponse.class) })
    
    @RequestMapping(value = "/steps",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Step> postStep(@ApiParam(value = "The step details" ,required=true )  @Valid @RequestBody NewStep body);

}
