/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ErrorResponse;
import io.swagger.model.NewTask;
import io.swagger.model.Task;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-14T13:49:00.734Z")

@Api(value = "tasks", description = "the tasks API")
public interface TasksApi {

    @ApiOperation(value = "Get a task", notes = "Get the task with the corresponding id", response = Task.class, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Information returned correctly", response = Task.class) })
    
    @RequestMapping(value = "/tasks/{task_id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Task> getTaskById(@ApiParam(value = "Task ID",required=true ) @PathVariable("task_id") Long taskId);


    @ApiOperation(value = "Get list of Tasks", notes = "Presents the list of tasks existing in the system", response = Task.class, responseContainer = "List", tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Information returned correctly", response = Task.class, responseContainer = "List") })
    
    @RequestMapping(value = "/tasks",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Task>> getTasks();


    @ApiOperation(value = "Creation of a new task", notes = "Creation of a new task", response = Task.class, tags={ "task", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Information returned correctly", response = Task.class),
        @ApiResponse(code = 403, message = "Error on creation of Task", response = ErrorResponse.class) })
    
    @RequestMapping(value = "/tasks",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Task> postTask(@ApiParam(value = "The task details" ,required=true )  @Valid @RequestBody NewTask body);

}
